# Generated by Django 5.1.6 on 2025-02-22 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_type', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
