# Generated by Django 5.1.6 on 2025-02-23 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_storage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='storage_type',
            new_name='storage_initial',
        ),
        migrations.AlterField(
            model_name='storage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
